# Generated by Django 4.1.1 on 2022-09-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='birthday',
        ),
    ]
